version: 0.0
os: windows

files:
  - source: files/index.html
    destination: C:\\inetpub\\wwwroot

permissions:
  - object: C:\\inetpub\\wwwroot
    pattern: index.html
    mode: 644
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.ps1
    - location: scripts/delete-old-index.ps1
  AfterInstall:
    - location: scripts/sleep.ps1
    - location: scripts/webserver-start.ps1
